anytv_main_homepage:
    path:  /{_locale}
    defaults: { _controller: AnytvMainBundle:Default:index, _locale: en }
    requirements:
        _locale:  %anytv.locales%
        
gamestm:
    path:      /games
    defaults:  { _controller: AnytvMainBundle:Default:gamestm }
    
cya:
    path:      /cya
    defaults:  { _controller: AnytvMainBundle:Default:cya }
    
heartbeat:
    path:      /heartbeat
    defaults:  { _controller: AnytvMainBundle:Default:heartbeat }
    
upload:
    path:      /upload/{_locale}
    defaults:  { _controller: AnytvMainBundle:Default:upload, _locale: en }
    requirements:
        _locale:  %anytv.locales%
        
emotionvfx:
    path:      /emotionvfx/{_locale}
    defaults:  { _controller: AnytvMainBundle:Default:emotionvfx, _locale: en }
    requirements:
        _locale:  %anytv.locales%
        
about:
    path:      /about/{_locale}
    defaults:  { _controller: AnytvMainBundle:Default:about, _locale: en }
    requirements:
        _locale:  %anytv.locales%
        
branding_kit:
    path:      /branding/{_locale}
    defaults:  { _controller: AnytvMainBundle:Default:brandingKit, _locale: en }
    requirements:
        _locale:  %anytv.locales%
       
live_stream_handbook:
    path:      /live_stream_handbook/{_locale}
    defaults:  { _controller: AnytvMainBundle:Default:liveStreamHandbook, _locale: en }
    requirements:
        _locale:  %anytv.locales%
        
recruiter_handbook:
    path:      /recruiter_handbook/{_locale}
    defaults:  { _controller: AnytvMainBundle:Default:recruiterHandbook, _locale: en }
    requirements:
        _locale:  %anytv.locales%
        
join_our_twitch_team:
    path:      /join_our_twitch_team/{_locale}
    defaults:  { _controller: AnytvMainBundle:Default:joinOurTwitchTeam, _locale: en }
    requirements:
        _locale:  %anytv.locales%
        
staff:
    path:      /staff/{_locale}
    defaults:  { _controller: AnytvMainBundle:Default:staff, _locale: en }
    requirements:
        _locale:  %anytv.locales%
        
faq:
    path:      /faq/{_locale}
    defaults:  { _controller: AnytvMainBundle:Default:faq, _locale: en }
    requirements:
        _locale:  %anytv.locales%
        
faq_category:
    path:      /faq/category/{_locale}/{id}
    defaults:  { _controller: AnytvMainBundle:Default:faqCategory, id: null, _locale: en }
    requirements:
        _locale:  %anytv.locales%
        
faq_spreadsheet:
    path:      /faq-spreadsheet/{_locale}
    defaults:  { _controller: AnytvMainBundle:Default:faqSpreadsheet, _locale: en }
    requirements:
        _locale:  %anytv.locales%
            
news_reset:
    path:      /{_locale}/admin/news/reset
    defaults:  { _controller: AnytvMainBundle:News:reset, _locale: en }
    requirements:
        _locale:  %anytv.locales%
        
news:
    path:      /{_locale}/admin/news/{page}
    defaults:  { _controller: AnytvMainBundle:News:index, _locale: en, page: 1 }
    requirements:
        _locale:  %anytv.locales%
        page:  \d+
       
news_add:
    path:      /{_locale}/admin/news/add
    defaults:  { _controller: AnytvMainBundle:News:add, _locale: en }
    requirements:
        _locale:  %anytv.locales%
    
news_edit:
    path:      /{_locale}/admin/news/edit/{id}
    defaults:  { _controller: AnytvMainBundle:News:edit, _locale: en }
    requirements:
        _locale:  %anytv.locales%
        id:  \d+
    
news_category:
    path:      /{_locale}/admin/news/categories/{page}
    defaults:  { _controller: AnytvMainBundle:NewsCategory:index, _locale: en, page: 1 }
    requirements:
        _locale:  %anytv.locales%
        page:  \d+
        
news_category_add:
    path:      /{_locale}/admin/news/categories/add
    defaults:  { _controller: AnytvMainBundle:NewsCategory:add, _locale: en }
    requirements:
        _locale:  %anytv.locales%
        
news_category_edit:
    path:      /{_locale}/admin/news/categories/edit/{id}
    defaults:  { _controller: AnytvMainBundle:NewsCategory:edit, _locale: en }
    requirements:
        _locale:  %anytv.locales%
        id:  \d+
